// <auto-generated />
using System;
using CapVerify.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CapVerify.Data.Migrations
{
    [DbContext(typeof(CapVerifyContext))]
    partial class CapVerifyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CapVerify.Domain.Models.TituloCapitalizacao", b =>
                {
                    b.Property<long>("TituloCaptalizacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataSorteio");

                    b.Property<DateTime>("DataVencimento");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<string>("Jogo");

                    b.Property<string>("UserId");

                    b.HasKey("TituloCaptalizacaoId");

                    b.HasIndex("UserId");

                    b.ToTable("TitulosCapitalizacao");
                });

            modelBuilder.Entity("CapVerify.Domain.Models.UserIdentity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("nvarchar")
                        .HasMaxLength(450);

                    b.Property<string>("Cpf");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar")
                        .HasMaxLength(256);

                    b.Property<string>("Name");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("CapVerify.Domain.Models.TituloCapitalizacao", b =>
                {
                    b.HasOne("CapVerify.Domain.Models.UserIdentity", "UserIdentity")
                        .WithMany()
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
